### ISSUE TITLE
When pasting text, it calls 2 time typingDone

### ISSUE THREAD

**Issue by smartland007** [HichemTab-tech/OTP-designer-jquery#3]
When we paste the code, it calls 2 times the function typingDone which cause unwanted result. Ex: calling an ajax function in typingDone to validate the OTP.

**Comment by HichemTab-tech** [comment]
Hello,

I just wanted to update you that I have identified and fixed the issue with the typingDone function being called twice. It was due to conflict with two functions. I have made the necessary adjustments in the code, and now the function is working as expected without any duplicate calls.

Thank you for bringing this to my attention. If you have any further questions or concerns, please feel free to let me know.

Best regards,
@HichemTab-tech
